M.mod_courseboard={is_admin:!1,is_category:!1,is_comment:!1,is_secret:!1,is_sns:!1,is_anonymous:!1,is_mobile:!1,www:''};M.mod_courseboard.init=function(Y,options){M.mod_courseboard.is_admin=options.is_admin;M.mod_courseboard.is_category=options.is_category;M.mod_courseboard.is_comment=options.is_comment;M.mod_courseboard.is_secret=options.is_secret;M.mod_courseboard.is_sns=options.is_sns
M.mod_courseboard.is_anonymous=options.is_anonymous;M.mod_courseboard.is_mobile=options.is_mobile;M.mod_courseboard.www=options.www}
M.mod_courseboard.list=function(Y,options){if(M.mod_courseboard.is_category){$(".courseboard_list #ub_category").change(function(){var select_value=$(this).val();if(select_value==""){move_url=options.courseboard_url.list}else{move_url=options.courseboard_url.category+'&caid='+select_value}
location.href=move_url});category_id=options.caid;if(category_id){$(".courseboard_list #ub_category > option[value='"+category_id+"']").attr("selected","selected")}}
if(options.search.is){$('.courseboard_list #ub_keyfield > option[value="'+options.search.field+'"]').attr('selected','selected');$('.courseboard_list button.search_cancel').click(function(){location.href=options.courseboard_url.list;return!1})}
if(M.mod_courseboard.is_admin){$(".courseboard_list .courseboard_table input[name='all_checked']").click(function(){var checked=$(this).is(":checked");$('.courseboard_list .courseboard_table input[name="manage[]"]').each(function(){if(!$(this).is(":disabled")){this.checked=checked}})});$(".courseboard_container .selected .check_delete").click(function(){var input_manage=$('.courseboard_list .courseboard_table input[name="manage[]"]:checked');if($(input_manage).length>0){if(confirm($(input_manage).length+options.i8n.selected_article_delete)){$('.courseboard_container .selected input[name="type"]').val('check_delete');$("#courseboard_list_form").submit()}}else{alert(options.i8n.no_selected_article)}
return!1});if(M.mod_courseboard.is_category){if(M.mod_courseboard.is_mobile){$("#article_move").modal({show:!1})}else{$("#article_move").modal('hide')}
$(".courseboard_container .selected .check_move").click(function(){var input_manage=$('.courseboard_list .courseboard_table input[name="manage[]"]:checked');if($(input_manage).length>0){if(M.mod_courseboard.is_mobile){$("#article_move").modal('show')}else{$("#article_move").modal('show')}}else{alert(options.i8n.no_selected_article)}
return!1});$("#article_move button.submit").click(function(){$('.courseboard_container .selected input[name="type"]').val('check_move');$('.courseboard_container .selected input[name="caid"]').val($("#ub_category_move").val());$("#courseboard_list_form").submit()})}}
$(".courseboard_container .sel_ls_change").on('change',function(){var ls=$(this).val();console.log(ls);if($.isNumeric(ls)){var queryParameters={},queryString=location.search.substring(1),re=/([^&=]+)=([^&]*)/g,m;while(m=re.exec(queryString)){queryParameters[decodeURIComponent(m[1])]=decodeURIComponent(m[2])}
queryParameters.ls=ls;queryParameters.page=1;location.search=$.param(queryParameters)}});$(".courseboard_container .btn_ls_change").click(function(){var ls=$(".courseboard_container input[name='ls']").val();if($.isNumeric(ls)){var queryParameters={},queryString=location.search.substring(1),re=/([^&=]+)=([^&]*)/g,m;while(m=re.exec(queryString)){queryParameters[decodeURIComponent(m[1])]=decodeURIComponent(m[2])}
queryParameters.ls=ls;queryParameters.page=1;location.search=$.param(queryParameters)}});if($(".ui-mobile-viewport").length>0){$(".ui-mobile-viewport .courseboard_list .group_select div.ui-select").next().remove()}}
M.mod_courseboard.my=function(Y,options){$(".courseboard_container .btn_ls_change").click(function(){var ls=$(".courseboard_container input[name='ls']").val();if($.isNumeric(ls)){var queryParameters={},queryString=location.search.substring(1),re=/([^&=]+)=([^&]*)/g,m;while(m=re.exec(queryString)){queryParameters[decodeURIComponent(m[1])]=decodeURIComponent(m[2])}
queryParameters.ls=ls;queryParameters.page=1;location.search=$.param(queryParameters)}});if(options.search.is){$('.courseboard_list #ub_keyfield > option[value="'+options.search.field+'"]').attr('selected','selected');$('.courseboard_list button.search_cancel').click(function(){location.href=options.search.cancel_url;return!1})}}
M.mod_courseboard.write=function(Y,options){$("#frm_courseboard").validate({submitHandler:function(form){if(!M.mod_courseboard.is_mobile){tinyMCE.triggerSave();if(!$(form.id_content).val()){alert(options.i8n.required_content);return!1}}
if($("#groupinfo").length>0){if(!$("#groupinfo").val()){alert(options.i8n.not_found_user_group);return!1}}
$(".courseboard_write .button_area button.submit").attr('disabled','disabled');showSubmitProgress();form.submit()}});$(".courseboard_write .button_area button.submit").click(function(){if(!M.mod_courseboard.is_mobile){tinyMCE.triggerSave()}});$(".courseboard_write .button_area button.cancel").click(function(){history.back(-1)});if(options.parent_secret){$("#secret").attr("checked","checked")}}
M.mod_courseboard.modify=function(Y,options){$("#frm_courseboard").validate({submitHandler:function(form){if(!M.mod_courseboard.is_mobile){tinyMCE.triggerSave();if(!$(form.id_content).val()){alert(options.i8n.required_content);return!1}}
$(".courseboard_write .button_area button.submit").attr('disabled','disabled');showSubmitProgress();form.submit()}});if(options.category.is){$("#category > option[value='"+options.category.id+"']").attr("selected","selected")}
if(options.notice.is){$("input[name='notice'][value='"+options.notice.id+"']").attr("checked","checked")}
$(".courseboard_write .button_area button.submit").click(function(){if(!M.mod_courseboard.is_mobile){tinyMCE.triggerSave()}});$(".courseboard_write .button_area button.cancel").click(function(){history.back(-1)})}
M.mod_courseboard.article=function(Y,options){if(M.mod_courseboard.is_mobile){$("#password_confirm").modal({show:!1})}else{$("#password_confirm").modal('hide')}
$("#password_confirm_form input.submit").click(function(){$("#password_confirm_form").submit()});$(".button_area .delete").click(function(){if(confirm(options.i8n.confirm_article_delete)){$("#password_confirm_form input[type='hidden'][name='type']").val("delete");if($(this).hasClass('delete_guest')){if(M.mod_courseboard.is_mobile){$("#password_confirm").modal('show')}else{$("#password_confirm").modal('show')}}else{return!0}}
return!1});if(M.mod_courseboard.is_comment){$(".frm_courseboard_cmt .courseboard_comment_editor button.cancel").click(function(){$(".frm_courseboard_cmt textarea#comment").val('')});$(".courseboard_comment .comment_modify").click(function(){var writer=$(this).parent().parent().find(".name");$("#comment_name").val(($(writer).find(".username").text()));$("#comment_email").val(($(writer).find(".email a").text()));var aid=$(this).attr("href").match(/[0-9]+$/);var cm=$(this).parent().parent().find(".comment_content");setCommentFormModify(M.mod_courseboard.www,aid,cm);return!1});$(".courseboard_comment .comment_delete").click(function(){if(confirm(options.i8n.confirm_comment_delete)){$("#password_confirm_form input[type='hidden'][name='type']").val("comment_delete");$("#password_confirm_form input[type='hidden'][name='bcid']").val($(this).attr("href").match(/[0-9]+$/));if($(this).hasClass('comment_delete_guest')){$("#password_confirm").modal('show')}else{$("#password_confirm_form").submit()}}
return!1});$(".courseboard_comment .comment_reply").click(function(){var aid=$(this).attr("href").match(/[0-9]+$/);comment_content=$(this).parent().parent().find(".comment_content");setCommentFormReply(aid,comment_content);return!1})}
$("a.lightbox_image").lightBox({imageLoading:options.lightbox.loading,imageBtnPrev:options.lightbox.prev,imageBtnNext:options.lightbox.next,imageBtnClose:options.lightbox.close,imageBlank:options.lightbox.block});if(M.mod_courseboard.is_sns){$("a.sns_send").click(function(){sns_send($(this).attr('href'),$(this).find('img').attr('alt'));return!1})}
$(".courseboard_view .text_to_html a").each(function(index){var alink=$(this).attr("href");var check_http=/^http:\/\/([a-z0-9-_\.]*)[\/\?]/i;var check_https=/^https:\/\/([a-z0-9-_\.]*)[\/\?]/i;if(alink.match(check_http)==null&&alink.match(check_https)==null){$(this).attr("href","#");$(this).attr("onclick","javascript:alert('해당 주소는 유해사이트로 접근 불가합니다.')")}})}
M.mod_courseboard.category=function(Y,options){if(M.mod_courseboard.is_category&&M.mod_courseboard.is_admin){$(".courseboard_list .courseboard_table .delete_category").click(function(){if(!confirm(options.i8n.confirm_category_delete)){return!1}});$(".courseboard_table tbody.sortable_table").sortable({handle:".orders",update:function(event,ui){var item="";var division="";$("table.courseboard_table tbody.sortable_table tr.sortable_row").each(function(i){ctid=$(this).attr("id");if(ctid){ctid=ctid.match(/[0-9]+$/);item+=division+ctid;division="^"}});param="type=category_sortable&idx="+item+"&id="+options.cm_id+"&cid="+options.course_id+"&bid="+options.courseboard_id;$.ajax({url:"action.php",data:param,type:'post',success:function(data){if(data.code==mesg.success){}else{alert(data.msg)}}})}}).disableSelection()}}
M.mod_courseboard.category_add=function(Y,options){$("#frm_courseboard").submit()}
M.mod_courseboard.category_modify=function(Y,options){$("#frm_courseboard").submit()}
function setCommentFormReply(aid,obj){var comment_form_clone=getCommentForm();$(comment_form_clone).find("input[type='hidden'][name='type']").val("comment_reply");$(comment_form_clone).find("input[type='hidden'][name='bcid']").val(aid);$(comment_form_clone).find('textarea').val('');$(obj).after(comment_form_clone)}
function setCommentFormModify(www,aid,obj){var comment_form_clone=getCommentForm();$(comment_form_clone).find("input[type='hidden'][name='type']").val("comment_modify");$(comment_form_clone).find("input[type='hidden'][name='bcid']").val(aid);$(obj).hide();$(obj).after(comment_form_clone);param="type=comment_info&cmid="+aid;$.ajax({url:www+"/mod/courseboard/ajax.php",data:param,type:'post',success:function(data){if(data.code==100){$(comment_form_clone).find('textarea').val(data.comment);if(M.mod_courseboard.is_anonymous&&$(comment_form_clone).find('#comment_name').length>0){$(comment_form_clone).find('#comment_name').val(data.name)}}else{alert(data.msg);setCommentCancel();return!1}}})}
function getCommentForm(){var comment_form_clone_name='courseboard_comment_form_clone';var comment_form_clone=$("#"+comment_form_clone_name);if(comment_form_clone.length>0){$(comment_form_clone).parent().find('.comment_content').show()}else{comment_form_clone=$("<div id='"+comment_form_clone_name+"' />").append($(".courseboard_comment .courseboard_comment_form").clone())}
$(comment_form_clone).find('button.cancel').unbind('click').click(function(){setCommentCancel()});return comment_form_clone}
function setCommentCancel(){var comment_form_clone_name='courseboard_comment_form_clone';var comment_form_clone=$("#"+comment_form_clone_name);if(comment_form_clone.length>0){$(comment_form_clone).parent().find('.comment_content').show()}
$(comment_form_clone).remove()}